export const ADMIN_LOGIN_REQUEST = "USER_LOGIN_REQUEST"
export const ADMIN_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS"
export const ADMIN_LOGIN_FAIL = "USER_LOGIN_FAIL"


export const ADMIN_FOODITEM_REQUEST = "ADMIN_FOODITEM_REQUEST"
export const ADMIN_FOODITEM_SUCCESS = "ADMIN_FOODITEM_SUCCESS"
export const ADMIN_FOODITEM_FAIL = "ADMIN_FOODITEM_FAIL"

export const ADMIN_LOGOUT = "ADMIN_LOGOUT"

export const ADMIN_DETAIL_REQUEST = "ADMIN_DETAIL_REQUEST"
export const ADMIN_DETAIL_SUCCESS = "ADMIN_DETAIL_SUCCESS"
export const ADMIN_DETAIL_FAIL = "ADMIN_DETAIL_FAIL"


export const ADMIN_DETAIL_EDIT_REQUEST = "ADMIN_DETAIL_EDIT_REQUEST"
export const ADMIN_DETAIL_EDIT_SUCCESS = "ADMIN_DETAIL_EDIT_SUCCESS"
export const ADMIN_DETAIL_EDIT_FAIL = "ADMIN_DETAIL_EDIT_FAIL"


export const ADMIN_DETAIL_DELETE_REQUEST = "ADMIN_DETAIL_DELETE_REQUEST"
export const ADMIN_DETAIL_DELETE_SUCCESS = "ADMIN_DETAIL_DELETE_SUCCESS"
export const ADMIN_DETAIL_DELETE_FAIL = "ADMIN_DETAIL_DELETE_FAIL"

export const ADMIN_ADDFOODITEM_REQUEST = "ADMIN_ADDFOODITEM_REQUEST"
export const ADMIN_ADDFOODITEM_SUCCESS = "ADMIN_ADDFOODITEM_SUCCESS"
export const ADMIN_ADDFOODITEM_FAIL = "ADMIN_ADDFOODITEM_FAIL"

export const ADMIN_USER_REQUEST = "ADMIN_USER_REQUEST"
export const ADMIN_USER_SUCCESS = "ADMIN_USER_SUCCESS"
export const ADMIN_USER_FAIL = "ADMIN_USER_FAIL"

export const ADMIN_ORDER_REQUEST = "ADMIN_ORDER_REQUEST"
export const ADMIN_ORDER_SUCCESS = "ADMIN_ORDER_SUCCESS"
export const ADMIN_ORDER_FAIL = "ADMIN_ORDER_FAIL"

export const ADD_CATEGORY_REQUEST = "ADD_CATEGORY_REQUEST"
export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS"
export const ADD_CATEGORY_FAIL = "ADD_CATEGORY_FAIL"