export const ADD_CART_REQUEST = "ADD_CART_REQUEST"
export const ADD_CART_SUCCESS = "ADD_CART_SUCCESS"
export const ADD_CART_FAIL = "ADD_CART_FAIL"


export const GET_CART_REQUEST = "GET_CART_REQUEST"
export const GET_CART_SUCCESS ="GET_CART_SUCCESS"
export const GET_CART_FAIL = "GET_CART_FAIL"

export const DELETE_CART_REQUEST = "DELETE_CART_REQUEST"
export const DELETE_CART_SUCCESS = "DELETE_CART_SUCCESS"
export const DELETE_CART_FAIL = "DELETE_CART_FAIL"

export const GET_PAYMENT_REQUEST = "GET_PAYMENT_REQUEST"
export const GET_PAYMENT_SUCCESS = "GET_PAYMENT_SUCCESS"
export const GET_PAYMENT_FAIL = "GET_PAYMENT_FAIL"

export const ORDER_PAYMENT_REQUEST = "ORDER_PAYMENT_REQUEST"
export const ORDER_PAYMENT_SUCCESS = "ORDER_PAYMENT_SUCCESS"
export const ORDER_PAYMENT_FAIL = "ORDER_PAYMENT_FAIL"