export const FOOD_ITEM_REQUEST = "FOOD_ITEM_REQUEST"
export const FOOD_ITEM_SUCCESS = "FOOD_ITEM_SUCCESS"
export const FOOD_ITEM_FAIL = "FOOD_ITEM_FAIL"

export const FOOD_ITEM_DETAIL_REQUEST = "FOOD_ITEM_DETAIL_REQUEST"
export const FOOD_ITEM_DETAIL_SUCCESS = "FOOD_ITEM_DETAIL_SUCCESS"
export const FOOD_ITEM_DETAIL_FAIL = "FOOD_ITEM_DETAIL_FAIL"


export const FOOD_ITEM_SIMILAR_REQUEST = "FOOD_ITEM_SIMILAR_REQUEST"
export const FOOD_ITEM_SIMILAR_SUCCESS = "FOOD_ITEM_SIMILAR_SUCCESS"
export const FOOD_ITEM_SIMILAR_FAIL ="FOOD_ITEM_SIMILAR_FAIL"

export const SPECIAL_FOOD_ITEM_REQUEST = "SPECIAL_FOOD_ITEM_REQUEST"
export const SPECIAL_FOOD_ITEM_SUCCESS = "SPECIAL_FOOD_ITEM_SUCCESS"
export const SPECIAL_FOOD_ITEM_FAIL = "SPECIAL_FOOD_ITEM_FAIL"

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST"
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS"
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL"