export const FOOD_ITEM_REQUEST = "FOOD_ITEM_REQUEST"
export const FOOD_ITEM_SUCCESS = "FOOD_ITEM_SUCCESS"
export const FOOD_ITEM_FAIL = "FOOD_ITEM_FAIL"

export const FOOD_ITEM_DETAIL_REQUEST = "FOOD_ITEM_DETAIL_REQUEST"
export const FOOD_ITEM_DETAIL_SUCCESS = "FOOD_ITEM_DETAIL_SUCCESS"
export const FOOD_ITEM_DETAIL_FAIL = "FOOD_ITEM_DETAIL_FAIL"


export const FOOD_ITEM_SIMILAR_REQUEST = "FOOD_ITEM_SIMILAR_REQUEST"
export const FOOD_ITEM_SIMILAR_SUCCESS = "FOOD_ITEM_SIMILAR_SUCCESS"
export const FOOD_ITEM_SIMILAR_FAIL ="FOOD_ITEM_SIMILAR_FAIL"

export const SPECIAL_FOOD_ITEM_REQUEST = "SPECIAL_FOOD_ITEM_REQUEST"
export const SPECIAL_FOOD_ITEM_SUCCESS = "SPECIAL_FOOD_ITEM_SUCCESS"
export const SPECIAL_FOOD_ITEM_FAIL = "SPECIAL_FOOD_ITEM_FAIL"

export const GET_CATEGORY_REQUEST = "GET_CATEGORY_REQUEST"
export const GET_CATEGORY_SUCCESS = "GET_CATEGORY_SUCCESS"
export const GET_CATEGORY_FAIL = "GET_CATEGORY_FAIL"

export const ADDTO_FAVOURATE_REQUEST = "ADDTO_FAVOURATE_REQUEST"
export const ADDTO_FAVOURATE_SUCCESS = "ADDTO_FAVOURATE_SUCCESS"
export const ADDTO_FAVOURATE_FAIL = "ADDTO_FAVOURATE_FAIL"

export const GET_FAVOURATE_REQUEST = "GET_FAVOURATE_REQUEST"
export const GET_FAVOURATE_SUCCESS = "GET_FAVOURATE_SUCCESS"
export const GET_FAVOURATE_FAIL = "GET_FAVOURATE_FAIL"

export const REMOVE_FAVOURATE_SUCCESS = "REMOVE_FAVOURATE_SUCCESS"
export const REMOVE_FAVOURATE_FAIL = "REMOVE_FAVOURATE_FAIL"

export const RECOMMEND_FAVOURATE_REQUEST = "RECOMMEND_FAVOURATE_REQUEST"
export const RECOMMEND_FAVOURATE_SUCCESS = "RECOMMEND_FAVOURATE_SUCCESS"
export const RECOMMEND_FAVOURATE_FAIL = "RECOMMEND_FAVOURATE_FAIL"

export const FOODITEM_RATING_SUCCESS = "FOODITEM_RATING_SUCCESS"
export const FOODITEM_RATING_FAIL = "FOODITEM_RATING_FAIL"